[package]
name = "tree_searching"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_enums = "0.8.5"
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.9.0"
seq-macro = "0.3.5"
